

PATCH = [
    "#new:Function $AllPartners",
    "{",
    "\tPUSH t0, t1, t2",
    "\tLIO t0, 8010F2AC %beginning of partners",
    "\tLIO t1, 8010F2F4 %end of partners",
    "\tORI t2, r0, 0100",
    "\t.loop",
    "\tSH t2, 0000 (t0)",
    "\tADDIU t0, t0, 08",
    "\tBEQ t0, t1, .end",
    "\tNOP",
    "\tBEQ r0, r0, .loop",
    "\tNOP",
    "\t.end",
    "\tSAH r0, 8010F2CC %remove goompa",
    "\tPOP t0, t1, t2",
    "\tJR ra",
    "\tNOP",
    "}",
    "",
    "#new:Function $HaveGoombario",
    "{",
    "\tPUSH t0, t1, t2",
    "\tLIO t0, 8010F2AC %beginning of partners",
    "\tLIO t1, 8010F2B4 %just do one",
    "\tORI t2, r0, 0100",
    "\t.loop",
    "\tSH t2, 0000 (t0)",
    "\tADDIU t0, t0, 08",
    "\tBEQ t0, t1, .end",
    "\tNOP",
    "\tBEQ r0, r0, .loop",
    "\tNOP",
    "\t.end",
    "\tSAH r0, 8010F2CC %remove goompa",
    "\tPOP t0, t1, t2",
    "\tJR ra",
    "\tNOP",
    "}",
    "",
    "#new:Function $UltraHammerandBoots",
    "{",
    "\tPUSH t0",
    "\tORI t0, r0, 0202",
    "\tSAH t0, 8010F290",
    "\tPOP t0",
    "\tJR RA",
    "\tNOP",
    "}",
    "",
    "#new:Function $HaveRegularHammer",
    "{",
    "\tPUSH t0",
    "\tORI t0, r0, 0000",
    "\tSAH t0, 8010F290",
    "\tPOP t0",
    "\tJR RA",
    "\tNOP",
    "}",
    "",
    "#new:Function $GiveMaxStarPower",
    "{",
    "\tPUSH t0",
    "\tORI t0, r0, 0007",
    "\tSAB t0, 8010F51E",
    "\tSAB t0, 8010F520",
    "\tPOP t0",
    "\tJR RA",
    "\tNOP",
    "}",
    "",
    "#new:Function $GetActionCommands",
    "{",
    "\t0:  ADDIU     V0, R0, 1",
    "\t4:  SAB       V0, 8010F29A",
    "\tC:  JR        RA",
    "\t10:  ADDIU     V0, R0, 2",
    "}",
    "",
    "#new:Function $SetPartnerGoombario",
    "{",
    "\tPUSH ra, t0",
    "\tLIA t0, 1",
    "\tSAB t0, 8010F2A2",
    "\tJPOP ra, t0",
    "\tNOP",
    "}",
    "",
]

GLOBAL_PATCH = [
    "@Hook 82758",
    "{",
    "\tJAL $GlobalMapScript",
    "\tNOP",
    "\t.end",
    "\tLIO     ra, 800E974C %set the RA to this value because at this point in code, it's always this",
    "\tJ        800E92B0",
    "\tNOP",
    "}",
    "",
    "#new:Function $WarpToMac00",
    "{",
    "\tPUSH t0, a0, a1, a2, ra",
    "\tLIO t0, 8003617C %value to change room pointer to",
    "\tSAH r0, 800A0944 %Room change state to 0",
    "\tSAW t0, 80151708 %Room change pointer",
    "\tORI a0, r0, 0001 %group value 1",
    "\tORI a1, r0, 0001 %room value 1",
    "\tORI a2, r0, 0004 %entrance value 4",
    "\tSAH a0, 800740AA %Group address",
    "\tSAH a1, 800740B0 %Room address",
    "\tSAH a2, 800740B2 %Entrance address",
    "\tPOP t0, a0, a1, a2, ra",
    "\tJR RA",
    "\tNOP",
    "}",
    "",
    "#new:Script:Map $GotoHome",
    "{",
    "\tCall $WarpToMac00()",
    "\tReturn",
    "\tEnd",
    "}",
    "",
    "#new:Function $GlobalMapScript",
    "{",
    "\tPUSH v1, a0, a1, a2, a3, ra",
    "\tLAH a0, 80074036 %one frame button presses",
    "\tORI a1, r0, 0800 %dpad up",
    "\tBNE a0, a1, .end",
    "\tNOP",
    "\tADDIU    a1, r0, 000A",
    "\tDADDU    a2, r0, r0",
    "\tLIO      a0, $GotoHome %script to load",
    "\tJAL     802C33E0 %Start Script",
    "\tNOP",
    "\t.end",
    "\tPOP v1, a0, a1, a2, a3, ra",
    "\tJR RA",
    "\tNOP",
    "}",
]
